---
# Ansible role to import a distro to cobbler - main.yml
#
# Copyright (C) 2016  Mark Einon <mark.einon@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License,
# Version 2.1 only as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

- name: mount the cdrom present in the machine's drive (virtual or otherwise)
  mount: name=/media/ src=/dev/sr0 fstype=iso9660 opts=ro state=present
  become: True

- name: import distro into cobbler
  command: cobbler import --arch=x86_64 --path=/media/ --name={{ distro_name }}
  ignore_errors: yes
  become: True

- name: copy kickstart profile for this distro (RH)
  copy: src={{ kickstart_path }} dest=/var/lib/cobbler/kickstarts/{{ distro_name }}.ks
  ignore_errors: yes
  become: True

- name: create a new cobbler profile for the kickstart
  command: cobbler profile edit --name={{ distro_name  }}-x86_64 --kickstart=/var/lib/cobbler/kickstarts/{{ distro_name }}.ks
  ignore_errors: yes
  become: True

- name: create a new cobbler system to use the profile
  command: cobbler system add --name=anscob-einon --profile={{ distro_name  }}-x86_64 --interface=eth0 --mac={{ pxe_mac }} --ip-address={{ pxe_ip }} --netboot-enabled=1 --static=1
  ignore_errors: yes
  become: True

- name: sync cobbler
  command: cobbler sync
  become: True

...
